# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar_pg_array_jruby}
  s.version = "0.9.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sokolov Yura aka funny_falcon"]
  s.date = %q{2011-06-05}
  s.description = %q{ar_pg_array includes support of PostgreSQL's int[], float[], text[], timestamptz[] etc. into ActiveRecord. You could define migrations for array columns, query on array columns.}
  s.email = %q{funny.falcon@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/ar_pg_array.rb",
    "lib/ar_pg_array/querying.rb",
    "lib/ar_pg_array/querying_arel.rb",
    "lib/ar_pg_array/references_by.rb",
    "lib/ar_pg_array/schema.rb",
    "lib/ar_pg_array/schema_arel.rb",
    "spec/fixtures/bulk.rb",
    "spec/fixtures/bulks.yml",
    "spec/fixtures/item.rb",
    "spec/fixtures/items.yml",
    "spec/fixtures/schema.rb",
    "spec/fixtures/tag.rb",
    "spec/fixtures/tags.yml",
    "spec/pg_array_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/funny-falcon/activerecord-postgresql-arrays}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ar-pg-array}
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Use power of PostgreSQL Arrays in ActiveRecord}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

